# Permalinks
permalink:       /:year-:month-:day/:title

# Setup
title:           bobbohee
description:     주로 개발 분야의 글을 올려요. ✏️
baseurl:         ''
url:             'https://park-bohee.github.io'

# Assets
sass:
  sass_dir:      _sass
  style:         :compressed

# Build settings
markdown:        kramdown

# About
author:
  name:          Park Bohee
  url:           https://park-bohee.github.io
  email:         bohee.at@gmail.com
  github:        park-bohee
  instagram:     bobbohee
  twitter:

# Custom vars
version:         1.0.0
github:
  repo:          https://github.com/park-bohee/park-bohee.github.io

# Google Analytics
google:
  analytics:
    tracking_id: G-6ZJZNLSB8E

# Jennifer
jennifer:
  analytics:
    tracking_id: 370bd56b