# Permalinks
permalink:       /:year-:month-:day/:title

# Setup
title:           bobbohee
description:     주로 개발 분야의 글을 올려요. ✏️
baseurl:         ''
url:             'https://park-bohee.github.io'

# Assets
sass:
  sass_dir:      _sass
  style:         :compressed

# Build settings
markdown:        kramdown

# About
author:
  name:          Park Bohee
  url:           https://bobbohee.github.io
  email:         bohee.at@gmail.com
  github:        bobbohee
  instagram:     bobbohee
  twitter:

# Custom vars
version:         1.0.0
github:
  repo:          https://github.com/bobbohee/bobbohee.github.io

# Google Analytics
google:
  analytics:
    tracking_id: G-NZGCKF91PL

# Jennifer
jennifer:
  analytics:
    tracking_id: 370bd56b

# Naver
naver:
  search:
    tracking_id: 5da5c4aff0bbac7f7ab43f6211bd796a03afe4c8